kind: pipeline
name: template

steps:
- name: build-and-test
  image: dkelosky/zowe-cli
  environment:
    USERNAME:
      from_secret: MF_USER
    PASSWORD:
      from_secret: MF_PASSWORD
  commands:
  - zowe profiles create zosmf default --user $USERNAME --password $PASSWORD --host usildamd.lvn.broadcom.net --rejectUnauthorized=false
  - "echo 'export default {'                      > config/local.ts"
  - "echo '    settings: {'                      >> config/local.ts"
  - "echo '        hlq: \"KELDA16.TEMP\",'       >> config/local.ts"
  - "echo '        account: \"105300000\",'      >> config/local.ts"
  - "echo '    },'                               >> config/local.ts"
  - "echo '}'                                    >> config/local.ts"
  - npm install
  - "npm run build:scripts"
  - npm run allocate
  - npm run upload
  - npm run test
  - npm run delete